DROP TABLE IF EXISTS Pessoa;

CREATE TABLE Pessoa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  sobrenome TEXT NOT NULL
);

DROP TABLE IF EXISTS SalaEvento;

CREATE TABLE SalaEvento (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  lotacao INTEGER NOT NULL
);

DROP TABLE IF EXISTS EspacoCafe;

CREATE TABLE EspacoCafe (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  lotacao INTEGER NOT NULL
);

DROP TABLE IF EXISTS SalaPessoa;

CREATE TABLE SalaPessoa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  SalaEvento_id INTEGER NOT NULL,
  Pessoa_id INTEGER NOT NULL,
  Etapa INTEGER NOT NULL,
  FOREIGN KEY(SalaEvento_id) REFERENCES SalaEvento(id),
  FOREIGN KEY(Pessoa_id) REFERENCES Pessoa(id)
);

DROP TABLE IF EXISTS EspacoPessoa;

CREATE TABLE EspacoPessoa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  EspacoCafe_id INTEGER NOT NULL,
  Pessoa_id INTEGER NOT NULL,
  Intervalo INTEGER NOT NULL,
  FOREIGN KEY(EspacoCafe_id) REFERENCES EspacoCafe(id),
  FOREIGN KEY(Pessoa_id) REFERENCES Pessoa(id)
);